### ISSUE TITLE
请问有train.py文件吗

### ISSUE THREAD

**Issue by Danki4** [Ekko-zn/AIGCDetectBenchmark#1]
您好，我非常膜拜你们实验室的新成果，但我在复现过程中遇到了一些困难，项目源码中似乎并没有train函数，是没有公开吗还是我没有找到，请您抽空之时回复我一下，祝科研顺利！！

**Comment by LoreImbo** [comment]
Nice work, I too would be very interested in the training and testing code of your method, namely RPTC.

**Comment by SleeplessBegonia** [comment]
> train的代码还在准备中，后续也会开源的，谢谢关注！

u r expected.
