### ISSUE TITLE
data_augment in process.py

### ISSUE THREAD

**Issue by OliverZhai1515** [Ekko-zn/AIGCDetectBenchmark#12]
https://github.com/Ekko-zn/AIGCDetectBenchmark/blob/5086947c8a415871ca824b14ec0c027e8d5b3a5a/data/process.py#L187-L211

**Comment by OliverZhai1515** [comment]
Hi~ Why removes the data_augment?

**Comment by Aemilia-xu** [comment]
I apologize for the misunderstanding caused by my mistake. Now, the data_augment used in training process has been added.

**Comment by OliverZhai1515** [comment]
Thanks for your reply! But I noticed your change doesn't work on val which is different from CNNDetection's code.
https://github.com/Ekko-zn/AIGCDetectBenchmark/blob/8c7524ee7f5b8a1d1bf4627ff855e57f531fa733/train.py#L28-L34
