### ISSUE TITLE
代码无法运行

### ISSUE THREAD

**Issue by RoyaltyLJW** [Ekko-zn/AIGCDetectBenchmark#4]
目前的代码中缺乏关于模型的核心函数实现导致代码无法运行
 network.trainer 以及eval_all中都有以下import
```python
 from util import get_model
```
该函数的实现应该是根据opt的模型名，定义model实例并返回。但是该函数没有实现。
此外，set_random_seed 也没有在util中实现，但该函数一定程度上可以去除，不影响基础使用

**Comment by Aemilia-xu** [comment]
感谢您的反馈，我们已经修复了util.py中的遗漏。
