### ISSUE TITLE
 question about your subtestset DALLE2

### ISSUE THREAD

**Issue by OliverZhai1515** [Ekko-zn/AIGCDetectBenchmark#8]
Thanks for your excellent work!
But I meet error when I try to open image `test/DALLE2/0_real/000000097792.jpg`.  I would like to know whether it was my operation that caused the damage to the picture or the sample itself.
![image](https://github.com/Ekko-zn/AIGCDetectBenchmark/assets/136923194/9f656bb6-e906-4ca0-9402-038dcace14fc)

Below is the image.
![000000097792](https://github.com/Ekko-zn/AIGCDetectBenchmark/assets/136923194/765ceb1f-5483-4ba3-9c8a-52fbd35acb8f)

**Comment by Aemilia-xu** [comment]
The sample itself is broken. And our original image is also damaged, so we can't provide an intact version. You can just delete it.

**Comment by OliverZhai1515** [comment]
Thanks for your reply :)
